name: Publicar no NPM (manual)

on:
  workflow_dispatch: # permite executar manualmente pelo GitHub

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4
        with:
          ref: main # garante que usa sempre a branch main

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'


      - name: Publicar no NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
